use crate::theme::Theme;
use regex::Regex;
use std::fs;
use std::path::Path;
use thiserror::Error;

pub const ASSET_DIR_NAME: &str = "zalo-theme";
pub const MARKER: &str = "data-zalo-theme-tool";
pub const STATE_FILE: &str = "theme-state.json";

#[derive(Debug, Error)]
pub enum CssError {
    #[error("{0}")]
    Failed(String),
    #[error(transparent)]
    Io(#[from] std::io::Error),
}

pub fn build_css(
    theme: &Theme,
    font_family: &str,
    font_weight: i32,
    font_size_percent: i32,
) -> String {
    let bg = theme.background.as_str();
    let fg = theme.foreground.as_str();
    let accent = theme.accent.as_str();
    let red = theme.red.as_deref().unwrap_or("#F85552");
    let yellow = theme.yellow.as_deref().unwrap_or("#E0AF68");
    let blue = theme.blue.as_deref().unwrap_or(accent);
    let cyan = theme.cyan.as_deref().unwrap_or(accent);
    let magenta = theme.magenta.as_deref().unwrap_or("#D3869B");
    let green = theme.green.as_deref().unwrap_or("#A7C080");
    let bright_black = theme
        .bright_black
        .clone()
        .unwrap_or_else(|| mix(fg, bg, 0.45));
    let bright_red = theme.bright_red.as_deref().unwrap_or(red);
    let bright_blue = theme.bright_blue.as_deref().unwrap_or(blue);
    let bright_magenta = theme.bright_magenta.as_deref().unwrap_or(magenta);
    let is_light = theme.is_light();
    let surface = mix(bg, "#FFFFFF", if is_light { 0.55 } else { 0.04 });
    let overlay = if is_light {
        mix(bg, fg, 0.08)
    } else {
        mix(bg, "#FFFFFF", 0.08)
    };
    let hl_low = if is_light {
        mix(bg, fg, 0.05)
    } else {
        mix(bg, "#FFFFFF", 0.05)
    };
    let hl_med = if is_light {
        mix(bg, fg, 0.14)
    } else {
        mix(bg, "#FFFFFF", 0.14)
    };
    let hl_high = if is_light {
        mix(bg, fg, 0.22)
    } else {
        mix(bg, "#FFFFFF", 0.22)
    };
    let muted = bright_black.clone();
    let subtle = mix(fg, bg, 0.25);
    let self_bubble = mix(accent, bg, if is_light { 0.82 } else { 0.75 });
    let self_border = mix(accent, bg, 0.55);
    let family = if font_family.is_empty() {
        "Maple Mono"
    } else {
        font_family
    };
    let weight = if font_weight == 0 { 600 } else { font_weight };
    let strong = (weight + 100).min(900);
    let size_percent = font_size_percent.clamp(80, 200);
    let size_scale = format!("{:.2}", size_percent as f64 / 100.0);
    let selection = theme
        .selection_bg
        .clone()
        .unwrap_or_else(|| rgba(accent, 0.35));
    let on_color = if is_light { "#FFFFFF" } else { bg };
    let ba100 = if is_light { "#fff".to_string() } else { fg.to_string() };

    format!(
        r#"/*
  ZaHue — {name}
  Source: terminalcolors.com / {id}
  Generated by ZaHue (native Rust)
*/
:root {{
  --zalo-ui-font: "{family}", ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif;
  --zalo-ui-weight: {weight};
  --zalo-ui-weight-strong: {strong};
  --zalo-ui-font-scale: {size_scale};
  --zalo-ui-font-size-percent: {size_percent}%;
  --medium: {weight};
  --semibold: {weight};
  --bold: {strong};
}}

/* Zalo uses rem extensively — scale the root to enlarge chat/UI text. */
html[data-zalo-theme="{id}"] {{
  font-size: {size_percent}% !important;
}}

html[data-zalo-theme="{id}"] {{
  --rp-base: {bg};
  --rp-surface: {surface};
  --rp-overlay: {overlay};
  --rp-muted: {muted};
  --rp-subtle: {subtle};
  --rp-text: {fg};
  --rp-love: {red};
  --rp-gold: {yellow};
  --rp-rose: {magenta};
  --rp-pine: {blue};
  --rp-foam: {cyan};
  --rp-iris: {bright_magenta};
  --rp-hl-low: {hl_low};
  --rp-hl-med: {hl_med};
  --rp-hl-high: {hl_high};
  --rp-self-bubble: {self_bubble};
  --rp-self-bubble-border: {self_border};
  --rp-self-selected: {self_selected};
  --rp-selection: {selection};
  --message-view-gradient: linear-gradient(to top, {hl_low}, {bg});
  --item-select: {item_select};
  --B10: {b10}; --B15: {b10};
  --B20: {b20}; --B25: {b20};
  --B30: {b30}; --B40: {b40};
  --B50: {cyan}; --B55: {cyan}; --B60: {blue}; --B70: {blue};
  --B80: {bright_blue}; --B85: {bright_blue}; --B90: {bright_blue}; --B95: {bright_blue}; --B100: {bright_blue};
  --B50-alpha-10: {b50a10}; --B50-alpha-20: {b50a20}; --B50-alpha-30: {b50a30};
  --R10: {r10}; --R15: {r10};
  --R20: {r20}; --R25: {r20};
  --R30: {r30}; --R40: {r40};
  --R50: {red}; --R55: {red}; --R60: {red}; --R70: {bright_red};
  --R80: {bright_red}; --R85: {bright_red}; --R90: {bright_red}; --R95: {bright_red}; --R100: {bright_red};
  --R50-alpha-10: {r50a10}; --R50-alpha-20: {r50a20}; --R50-alpha-30: {r50a30};
  --OR50: {yellow}; --OR55: {yellow}; --OR60: {yellow};
  --Y50: {yellow}; --Y60: {yellow};
  --G50: {green}; --G60: {green};
  --P50: {magenta}; --P60: {magenta};
  --PK50: {bright_magenta}; --PK60: {bright_magenta};
  --BA0: transparent; --BA10: {ba10}; --BA20: {ba20}; --BA30: {ba30};
  --BA40: {ba40}; --BA50: {ba50}; --BA70: {ba70}; --BA80: {ba80};
  --BA100: {ba100};
  --WA0: transparent; --WA10: {wa10}; --WA15: {wa15}; --WA50: {wa50};
  --WA70: {wa70}; --WA80: {wa80}; --WA100: {surface};

  --N10: var(--rp-hl-low); --N15: var(--rp-hl-low); --N20: var(--rp-overlay); --N25: var(--rp-overlay);
  --N30: var(--rp-hl-med); --N40: var(--rp-muted); --N50: var(--rp-muted); --N60: var(--rp-subtle);
  --N70: var(--rp-subtle); --N80: var(--rp-subtle); --N90: var(--rp-text); --N100: var(--rp-text);
  --N200: var(--rp-text); --N300: var(--rp-text); --N350: var(--rp-text);
  --NG10: var(--rp-base); --NG15: var(--rp-base); --NG20: var(--rp-overlay); --NG25: var(--rp-overlay);
  --NG30: var(--rp-hl-med); --NG40: var(--rp-muted); --NG50: var(--rp-muted); --NG55: var(--rp-subtle);
  --NG60: var(--rp-subtle); --NG70: var(--rp-text); --NG80: var(--rp-text); --NG85: var(--rp-text);
  --NG90: var(--rp-text); --NG95: var(--rp-text); --NG100: var(--rp-text);

  --bg-default: var(--rp-surface); --title-bar: var(--rp-base);
  --surface-background: var(--rp-base); --surface-background-subtle: var(--rp-hl-low);
  --surface-alt: var(--rp-surface); --surface-background-overlay: var(--rp-overlay);
  --layer-background: var(--rp-surface); --layer-background-subtle: var(--rp-base);
  --layer-background-hover: var(--rp-hl-low); --layer-background-disabled: var(--rp-overlay);
  --layer-background-selected: var(--item-select); --layer-background-inverse: var(--rp-text);
  --layer-background-inverse-subtle: var(--rp-subtle);
  --layer-background-leftmenu: var(--rp-base); --layer-background-leftmenu-hover: var(--rp-overlay);
  --layer-background-leftmenu-selected: var(--rp-overlay);
  --layer-background-navbar-normal: var(--rp-base); --layer-background-navbar-hover: var(--rp-overlay);
  --layer-background-navbar-selected: var(--rp-overlay);
  --text-primary: var(--rp-text); --text-primary-50: {text_primary_50};
  --text-secondary: var(--rp-subtle); --text-placeholder: var(--rp-muted); --text-disabled: var(--rp-muted);
  --text-on-color: {on_color}; --text-errors: var(--rp-love); --text-success: var(--rp-foam);
  --text-warning: var(--rp-gold); --text-information: var(--rp-pine); --text-mention: var(--rp-pine);
  --icon-primary: var(--rp-subtle); --icon-secondary: var(--rp-muted); --icon-disabled: var(--rp-muted);
  --icon-on-color: {on_color}; --icon-errors: var(--rp-love); --icon-success: var(--rp-foam);
  --icon-warning: var(--rp-gold); --icon-information: var(--rp-pine);
  --icon-count-noti-enable-bg: var(--rp-love); --icon-count-noti-disable-bg: var(--rp-muted);
  --border: var(--rp-hl-med); --border-subtle: var(--rp-hl-low); --border-bold: var(--rp-hl-high);
  --border-disabled: var(--rp-hl-med); --border-focused: var(--rp-foam); --border-selected: var(--rp-pine);
  --border-errors: var(--rp-love); --border-success: var(--rp-foam); --border-warning: var(--rp-gold);
  --border-information: var(--rp-pine); --divider: var(--rp-hl-med); --divider-subtle: var(--rp-hl-low); --divider-bold: var(--rp-hl-high);
  --link: var(--rp-pine); --success: var(--rp-foam); --tab-txt: var(--rp-subtle); --tab-inactive: var(--rp-subtle); --tab-active: var(--rp-pine);
  --scrollbar: var(--rp-hl-high); --scrollbar-opacity: 0.55; --selection: var(--rp-selection); --selection-text: var(--rp-text);
  --blue-message: var(--rp-self-bubble); --blue-message-selected: var(--rp-self-selected);
  --blue-message-selected-border: var(--rp-self-bubble-border); --blue-message-border: var(--rp-self-bubble-border);
  --blue-message-action: var(--rp-self-selected); --blue-message-action-border: var(--rp-self-bubble-border);
  --blue-message-btn: var(--rp-overlay); --blue-message-btn-border: var(--rp-hl-med);
  --blue-quote: var(--rp-overlay); --blue-quote-selected: var(--rp-overlay); --blue-quote-border: var(--rp-self-bubble-border);
  --blue-quote-line: var(--rp-foam); --blue-link: var(--rp-pine); --blue-file-progress-track: var(--rp-overlay); --blue-message-shadow: transparent;
  --white-message: var(--rp-surface); --white-message-selected: var(--rp-hl-low); --white-message-selected-border: var(--rp-hl-med);
  --white-message-border: var(--rp-hl-med); --white-message-action: var(--rp-base); --white-message-action-border: var(--rp-hl-med);
  --white-message-btn: var(--rp-overlay); --white-message-btn-border: var(--rp-hl-med);
  --white-quote: var(--rp-hl-low); --white-quote-selected: var(--rp-hl-low); --white-quote-border: var(--rp-hl-med);
  --white-quote-line: var(--rp-iris); --white-link: var(--rp-pine); --white-file-progress-track: var(--rp-hl-med);
  --button-primary-normal: var(--rp-pine); --button-primary-hover: var(--rp-foam); --button-primary-pressed: var(--rp-pine);
  --button-primary-text: {on_color}; --button-secondary-normal: {btn_sec};
  --button-secondary-hover: {btn_sec_hover}; --button-secondary-text: var(--rp-pine);
  --button-danger-normal: var(--rp-love); --button-danger-text: {on_color};
  --input-field-bg-filled: var(--rp-overlay); --input-field-bg-filled-hover: var(--rp-hl-med);
  --field-bg-filled: var(--rp-overlay); --field-bg-filled-hover: var(--rp-hl-med);
  --field-bg-outline: var(--rp-surface); --field-bg-outline-hover: var(--rp-hl-low);
  --item-wa-hover: var(--rp-hl-low); --item-wa-select: var(--item-select); --brand-primary: var(--rp-pine);
}}

html[data-zalo-theme="{id}"] body.zalo-theme {{
  font-family: var(--zalo-ui-font) !important;
  font-weight: var(--zalo-ui-weight) !important;
  background-color: var(--rp-surface);
  color: var(--rp-text);
  -webkit-font-smoothing: antialiased;
}}

html[data-zalo-theme="{id}"] body.zalo-theme .message-view,
html[data-zalo-theme="{id}"] body.zalo-theme .card--text,
html[data-zalo-theme="{id}"] body.zalo-theme .rich-input,
html[data-zalo-theme="{id}"] body.zalo-theme .rich-text-input,
html[data-zalo-theme="{id}"] body.zalo-theme .chat-box-input__content__input,
html[data-zalo-theme="{id}"] body.zalo-theme .conv-message,
html[data-zalo-theme="{id}"] body.zalo-theme .z-conv-message,
html[data-zalo-theme="{id}"] body.zalo-theme .chat-info-general__item--title,
html[data-zalo-theme="{id}"] body.zalo-theme .title-name {{
  font-family: var(--zalo-ui-font) !important;
  font-weight: var(--zalo-ui-weight) !important;
}}

html[data-zalo-theme="{id}"] body.zalo-theme b,
html[data-zalo-theme="{id}"] body.zalo-theme strong,
html[data-zalo-theme="{id}"] body.zalo-theme .font-semibold,
html[data-zalo-theme="{id}"] body.zalo-theme [style*="font-weight: 500"],
html[data-zalo-theme="{id}"] body.zalo-theme [style*="font-weight:500"] {{
  font-weight: var(--zalo-ui-weight-strong) !important;
}}

html[data-zalo-theme="{id}"] body.zalo-theme .message-view__blur__overlay,
html[data-zalo-theme="{id}"] body.zalo-theme .message-view__blur__overlay_noavatar {{
  background-image: var(--message-view-gradient) !important;
}}

html[data-zalo-theme="{id}"] body.zalo-theme #main-tab {{ border-right: 1px solid var(--border); }}
html[data-zalo-theme="{id}"] body.zalo-theme.zalo-theme--darwin .nav__tabs__zalo {{
  padding-top: 40px; padding-bottom: 16px; height: auto;
}}
html[data-zalo-theme="{id}"] body.zalo-theme .leftbar-tab {{ color: var(--rp-subtle); }}
html[data-zalo-theme="{id}"] body.zalo-theme .leftbar-tab:hover,
html[data-zalo-theme="{id}"] body.zalo-theme .leftbar-tab.selected {{ color: var(--rp-pine); }}
html[data-zalo-theme="{id}"] body.zalo-theme .card.me {{
  background-color: var(--blue-message); border-color: var(--blue-message-border);
}}
html[data-zalo-theme="{id}"] body.zalo-theme .card:not(.me) {{
  background-color: var(--white-message); border-color: var(--white-message-border);
}}
html[data-zalo-theme="{id}"] body.zalo-theme ::selection {{
  background: var(--selection) !important; color: var(--selection-text) !important;
}}
html[data-zalo-theme="{id}"] body.zalo-theme div::-webkit-scrollbar-thumb {{
  background: var(--scrollbar) !important; opacity: var(--scrollbar-opacity) !important;
}}
html[data-zalo-theme="{id}"] body.zalo-theme .setting-section:has(> .setting-section-content__theme) {{
  display: none;
}}
"#,
        name = theme.name,
        id = theme.id,
        family = family,
        weight = weight,
        strong = strong,
        size_scale = size_scale,
        size_percent = size_percent,
        bg = bg,
        surface = surface,
        overlay = overlay,
        muted = muted,
        subtle = subtle,
        fg = fg,
        red = red,
        yellow = yellow,
        magenta = magenta,
        blue = blue,
        cyan = cyan,
        bright_magenta = bright_magenta,
        hl_low = hl_low,
        hl_med = hl_med,
        hl_high = hl_high,
        self_bubble = self_bubble,
        self_border = self_border,
        self_selected = mix(&self_bubble, accent, 0.18),
        selection = selection,
        item_select = mix(accent, bg, 0.82),
        b10 = mix(blue, bg, 0.85),
        b20 = mix(blue, bg, 0.7),
        b30 = mix(blue, bg, 0.45),
        b40 = mix(blue, bg, 0.2),
        bright_blue = bright_blue,
        b50a10 = rgba(cyan, 0.1),
        b50a20 = rgba(cyan, 0.2),
        b50a30 = rgba(cyan, 0.3),
        r10 = mix(red, bg, 0.85),
        r20 = mix(red, bg, 0.7),
        r30 = mix(red, bg, 0.45),
        r40 = mix(red, bg, 0.2),
        bright_red = bright_red,
        r50a10 = rgba(red, 0.1),
        r50a20 = rgba(red, 0.2),
        r50a30 = rgba(red, 0.3),
        green = green,
        ba10 = rgba(fg, 0.08),
        ba20 = rgba(fg, 0.12),
        ba30 = rgba(fg, 0.18),
        ba40 = rgba(fg, 0.25),
        ba50 = rgba(fg, 0.35),
        ba70 = rgba(fg, 0.55),
        ba80 = rgba(fg, 0.7),
        ba100 = ba100,
        wa10 = rgba(bg, 0.4),
        wa15 = rgba(&overlay, 0.7),
        wa50 = rgba(&surface, 0.7),
        wa70 = rgba(&surface, 0.85),
        wa80 = rgba(&surface, 0.92),
        text_primary_50 = rgba(fg, 0.55),
        on_color = on_color,
        btn_sec = rgba(cyan, 0.12),
        btn_sec_hover = rgba(cyan, 0.2),
    )
}

pub fn build_js(theme_id: &str) -> String {
    let theme_lit = serde_json::to_string(theme_id).unwrap_or_else(|_| format!("\"{theme_id}\""));
    format!(
        r#"/*
  ZaHue bootstrap — {theme_id}
*/
(function () {{
  const THEME = {theme_lit}
  const html = document.documentElement
  const body = document.body
  html.setAttribute('data-zalo-theme', THEME)
  body.classList.add('zalo-theme')
  body.classList.remove('zalo-maple-dawn', 'zalo-maple-dawn--darwin')
  if (html.getAttribute('data-zalo-os') === 'macOS') body.classList.add('zalo-theme--darwin')
  console.info('[zahue]', THEME, 'active')
}})()
"#
    )
}

/// Patch pc-dist/index.html for Windows (data-zalo-os="Windows", body.zalo-theme, no darwin).
pub fn patch_index_html(app_root: &Path, theme_id: &str) -> Result<(), CssError> {
    let index_path = app_root.join("pc-dist/index.html");
    if !index_path.is_file() {
        return Err(CssError::Failed(format!(
            "Missing {}",
            index_path.display()
        )));
    }
    let mut html = fs::read_to_string(&index_path)?;

    let patterns = [
        r#"<link[^>]*data-zalo-theme-tool="1"[^>]*>"#,
        r#"<script[^>]*data-zalo-theme-tool="1"[^>]*></script>"#,
        r#"<link[^>]*href="[^"]*zalo-theme/theme\.css"[^>]*>"#,
        r#"<script[^>]*src="[^"]*zalo-theme/theme\.js"[^>]*></script>"#,
        r#"<link[^>]*href="[^"]*zalo-maple-dawn/[^"]*"[^>]*>"#,
        r#"<script[^>]*src="[^"]*zalo-maple-dawn/[^"]*"[^>]*></script>"#,
    ];
    for pat in patterns {
        let re = Regex::new(pat).map_err(|e| CssError::Failed(e.to_string()))?;
        html = re.replace_all(&html, "").into_owned();
    }

    let link = format!(
        r#"<link rel="stylesheet" href="{ASSET_DIR_NAME}/theme.css" {MARKER}="1">"#
    );
    let script = format!(r#"<script src="{ASSET_DIR_NAME}/theme.js" {MARKER}="1"></script>"#);

    if let Some(idx) = html.to_ascii_lowercase().find("</head>") {
        html.insert_str(idx, &format!("{link}\n"));
    } else {
        html.push_str(&format!("\n{link}\n"));
    }
    // recompute after first insert
    if let Some(idx) = html.to_ascii_lowercase().find("</body>") {
        html.insert_str(idx, &format!("{script}\n"));
    } else {
        html.push_str(&format!("\n{script}\n"));
    }

    let os_re = Regex::new(r#"data-zalo-os="[^"]*""#).unwrap();
    if os_re.is_match(&html) {
        html = os_re.replace(&html, r#"data-zalo-os="Windows""#).into_owned();
    } else {
        let html_re = Regex::new(r"(?i)<html").unwrap();
        html = html_re
            .replace(&html, r#"<html data-zalo-os="Windows""#)
            .into_owned();
    }

    let theme_re = Regex::new(r#"data-zalo-theme="[^"]*""#).unwrap();
    if theme_re.is_match(&html) {
        html = theme_re
            .replace(&html, format!(r#"data-zalo-theme="{theme_id}""#).as_str())
            .into_owned();
    } else {
        let html_re = Regex::new(r"(?i)<html").unwrap();
        html = html_re
            .replace(
                &html,
                format!(r#"<html data-zalo-theme="{theme_id}""#).as_str(),
            )
            .into_owned();
    }

    let body_re = Regex::new(r"(?i)<body[^>]*>").unwrap();
    if let Some(m) = body_re.find(&html) {
        let mut tag = m.as_str().to_string();
        tag = tag.replace("zalo-maple-dawn--darwin", "");
        tag = tag.replace("zalo-maple-dawn", "");
        tag = tag.replace("zalo-theme--darwin", "");
        if !tag.contains("zalo-theme") {
            let class_re = Regex::new(r#"class="([^"]*)""#).unwrap();
            if class_re.is_match(&tag) {
                tag = class_re
                    .replace(&tag, |caps: &regex::Captures| {
                        let inner = caps.get(1).map(|m| m.as_str()).unwrap_or("").trim();
                        if inner.is_empty() {
                            r#"class="zalo-theme""#.to_string()
                        } else {
                            format!(r#"class="{inner} zalo-theme""#)
                        }
                    })
                    .into_owned();
            } else {
                let body_open = Regex::new(r"(?i)<body").unwrap();
                tag = body_open
                    .replace(&tag, r#"<body class="zalo-theme""#)
                    .into_owned();
            }
        }
        html.replace_range(m.start()..m.end(), &tag);
    }

    let csp_re =
        Regex::new(r#"(?i)<meta[^>]*http-equiv="Content-Security-Policy"[^>]*>"#).unwrap();
    if let Some(m) = csp_re.find(&html.clone()) {
        let mut meta = m.as_str().to_string();
        if meta.contains("style-src") && !meta.contains("'unsafe-inline'") {
            let style_re = Regex::new(r#"style-src([^;"]*)"#).unwrap();
            meta = style_re
                .replace(&meta, "style-src$1 'unsafe-inline'")
                .into_owned();
            html.replace_range(m.start()..m.end(), &meta);
        }
    }

    fs::write(&index_path, html)?;
    Ok(())
}

pub fn mix(a: &str, b: &str, t: f64) -> String {
    let (ar, ag, ab) = rgb(a);
    let (br, bg, bb) = rgb(b);
    let r = (ar as f64 + (br as f64 - ar as f64) * t).round() as i32;
    let g = (ag as f64 + (bg as f64 - ag as f64) * t).round() as i32;
    let b = (ab as f64 + (bb as f64 - ab as f64) * t).round() as i32;
    format!("#{:02X}{:02X}{:02X}", clamp(r), clamp(g), clamp(b))
}

pub fn rgba(hex: &str, alpha: f64) -> String {
    let (r, g, b) = rgb(hex);
    format!("rgba({r}, {g}, {b}, {alpha:.3})")
}

fn rgb(hex: &str) -> (i32, i32, i32) {
    let cleaned: String = hex.chars().filter(|c| c.is_ascii_hexdigit()).collect();
    let value = u32::from_str_radix(&cleaned, 16).unwrap_or(0);
    (
        ((value >> 16) & 0xFF) as i32,
        ((value >> 8) & 0xFF) as i32,
        (value & 0xFF) as i32,
    )
}

fn clamp(n: i32) -> i32 {
    n.clamp(0, 255)
}
