import Foundation

enum ThemeCSSBuilder {
    static let assetDirName = "zalo-theme"
    static let marker = "data-zalo-theme-tool"
    static let stateFile = "theme-state.json"

    static func css(theme: ThemeDefinition, fontFamily: String, fontWeight: Int) -> String {
        let bg = theme.background
        let fg = theme.foreground
        let accent = theme.accent
        let red = theme.red ?? "#F85552"
        let yellow = theme.yellow ?? "#E0AF68"
        let blue = theme.blue ?? accent
        let cyan = theme.cyan ?? accent
        let magenta = theme.magenta ?? "#D3869B"
        let green = theme.green ?? "#A7C080"
        let brightBlack = theme.brightBlack ?? HexColor.mix(fg, bg, 0.45)
        let brightRed = theme.brightRed ?? red
        let brightBlue = theme.brightBlue ?? blue
        let brightMagenta = theme.brightMagenta ?? magenta
        let isLight = theme.isLight
        let surface = HexColor.mix(bg, "#FFFFFF", isLight ? 0.55 : 0.04)
        let overlay = isLight ? HexColor.mix(bg, fg, 0.08) : HexColor.mix(bg, "#FFFFFF", 0.08)
        let hlLow = isLight ? HexColor.mix(bg, fg, 0.05) : HexColor.mix(bg, "#FFFFFF", 0.05)
        let hlMed = isLight ? HexColor.mix(bg, fg, 0.14) : HexColor.mix(bg, "#FFFFFF", 0.14)
        let hlHigh = isLight ? HexColor.mix(bg, fg, 0.22) : HexColor.mix(bg, "#FFFFFF", 0.22)
        let muted = brightBlack
        let subtle = HexColor.mix(fg, bg, 0.25)
        let selfBubble = HexColor.mix(accent, bg, isLight ? 0.82 : 0.75)
        let selfBorder = HexColor.mix(accent, bg, 0.55)
        let family = fontFamily.isEmpty ? "Maple Mono" : fontFamily
        let weight = fontWeight == 0 ? 600 : fontWeight
        let strong = min(900, weight + 100)
        let selection = theme.selectionBg ?? HexColor.rgba(accent, 0.35)
        let onColor = isLight ? "#FFFFFF" : bg

        return """
        /*
          Zalo Theme — \(theme.name)
          Source: terminalcolors.com / \(theme.id)
          Generated by native Swift installer
        */
        :root {
          --zalo-ui-font: "\(family)", ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif;
          --zalo-ui-weight: \(weight);
          --zalo-ui-weight-strong: \(strong);
          --medium: \(weight);
          --semibold: \(weight);
          --bold: \(strong);
        }

        html[data-zalo-theme="\(theme.id)"] {
          --rp-base: \(bg);
          --rp-surface: \(surface);
          --rp-overlay: \(overlay);
          --rp-muted: \(muted);
          --rp-subtle: \(subtle);
          --rp-text: \(fg);
          --rp-love: \(red);
          --rp-gold: \(yellow);
          --rp-rose: \(magenta);
          --rp-pine: \(blue);
          --rp-foam: \(cyan);
          --rp-iris: \(brightMagenta);
          --rp-hl-low: \(hlLow);
          --rp-hl-med: \(hlMed);
          --rp-hl-high: \(hlHigh);
          --rp-self-bubble: \(selfBubble);
          --rp-self-bubble-border: \(selfBorder);
          --rp-self-selected: \(HexColor.mix(selfBubble, accent, 0.18));
          --rp-selection: \(selection);
          --message-view-gradient: linear-gradient(to top, \(hlLow), \(bg));
          --item-select: \(HexColor.mix(accent, bg, 0.82));
          --B10: \(HexColor.mix(blue, bg, 0.85)); --B15: \(HexColor.mix(blue, bg, 0.85));
          --B20: \(HexColor.mix(blue, bg, 0.7)); --B25: \(HexColor.mix(blue, bg, 0.7));
          --B30: \(HexColor.mix(blue, bg, 0.45)); --B40: \(HexColor.mix(blue, bg, 0.2));
          --B50: \(cyan); --B55: \(cyan); --B60: \(blue); --B70: \(blue);
          --B80: \(brightBlue); --B85: \(brightBlue); --B90: \(brightBlue); --B95: \(brightBlue); --B100: \(brightBlue);
          --B50-alpha-10: \(HexColor.rgba(cyan, 0.1)); --B50-alpha-20: \(HexColor.rgba(cyan, 0.2)); --B50-alpha-30: \(HexColor.rgba(cyan, 0.3));
          --R10: \(HexColor.mix(red, bg, 0.85)); --R15: \(HexColor.mix(red, bg, 0.85));
          --R20: \(HexColor.mix(red, bg, 0.7)); --R25: \(HexColor.mix(red, bg, 0.7));
          --R30: \(HexColor.mix(red, bg, 0.45)); --R40: \(HexColor.mix(red, bg, 0.2));
          --R50: \(red); --R55: \(red); --R60: \(red); --R70: \(brightRed);
          --R80: \(brightRed); --R85: \(brightRed); --R90: \(brightRed); --R95: \(brightRed); --R100: \(brightRed);
          --R50-alpha-10: \(HexColor.rgba(red, 0.1)); --R50-alpha-20: \(HexColor.rgba(red, 0.2)); --R50-alpha-30: \(HexColor.rgba(red, 0.3));
          --OR50: \(yellow); --OR55: \(yellow); --OR60: \(yellow);
          --Y50: \(yellow); --Y60: \(yellow);
          --G50: \(green); --G60: \(green);
          --P50: \(magenta); --P60: \(magenta);
          --PK50: \(brightMagenta); --PK60: \(brightMagenta);
          --BA0: transparent; --BA10: \(HexColor.rgba(fg, 0.08)); --BA20: \(HexColor.rgba(fg, 0.12)); --BA30: \(HexColor.rgba(fg, 0.18));
          --BA40: \(HexColor.rgba(fg, 0.25)); --BA50: \(HexColor.rgba(fg, 0.35)); --BA70: \(HexColor.rgba(fg, 0.55)); --BA80: \(HexColor.rgba(fg, 0.7));
          --BA100: \(isLight ? "#fff" : fg);
          --WA0: transparent; --WA10: \(HexColor.rgba(bg, 0.4)); --WA15: \(HexColor.rgba(overlay, 0.7)); --WA50: \(HexColor.rgba(surface, 0.7));
          --WA70: \(HexColor.rgba(surface, 0.85)); --WA80: \(HexColor.rgba(surface, 0.92)); --WA100: \(surface);

          --N10: var(--rp-hl-low); --N15: var(--rp-hl-low); --N20: var(--rp-overlay); --N25: var(--rp-overlay);
          --N30: var(--rp-hl-med); --N40: var(--rp-muted); --N50: var(--rp-muted); --N60: var(--rp-subtle);
          --N70: var(--rp-subtle); --N80: var(--rp-subtle); --N90: var(--rp-text); --N100: var(--rp-text);
          --N200: var(--rp-text); --N300: var(--rp-text); --N350: var(--rp-text);
          --NG10: var(--rp-base); --NG15: var(--rp-base); --NG20: var(--rp-overlay); --NG25: var(--rp-overlay);
          --NG30: var(--rp-hl-med); --NG40: var(--rp-muted); --NG50: var(--rp-muted); --NG55: var(--rp-subtle);
          --NG60: var(--rp-subtle); --NG70: var(--rp-text); --NG80: var(--rp-text); --NG85: var(--rp-text);
          --NG90: var(--rp-text); --NG95: var(--rp-text); --NG100: var(--rp-text);

          --bg-default: var(--rp-surface); --title-bar: var(--rp-base);
          --surface-background: var(--rp-base); --surface-background-subtle: var(--rp-hl-low);
          --surface-alt: var(--rp-surface); --surface-background-overlay: var(--rp-overlay);
          --layer-background: var(--rp-surface); --layer-background-subtle: var(--rp-base);
          --layer-background-hover: var(--rp-hl-low); --layer-background-disabled: var(--rp-overlay);
          --layer-background-selected: var(--item-select); --layer-background-inverse: var(--rp-text);
          --layer-background-inverse-subtle: var(--rp-subtle);
          --layer-background-leftmenu: var(--rp-base); --layer-background-leftmenu-hover: var(--rp-overlay);
          --layer-background-leftmenu-selected: var(--rp-overlay);
          --layer-background-navbar-normal: var(--rp-base); --layer-background-navbar-hover: var(--rp-overlay);
          --layer-background-navbar-selected: var(--rp-overlay);
          --text-primary: var(--rp-text); --text-primary-50: \(HexColor.rgba(fg, 0.55));
          --text-secondary: var(--rp-subtle); --text-placeholder: var(--rp-muted); --text-disabled: var(--rp-muted);
          --text-on-color: \(onColor); --text-errors: var(--rp-love); --text-success: var(--rp-foam);
          --text-warning: var(--rp-gold); --text-information: var(--rp-pine); --text-mention: var(--rp-pine);
          --icon-primary: var(--rp-subtle); --icon-secondary: var(--rp-muted); --icon-disabled: var(--rp-muted);
          --icon-on-color: \(onColor); --icon-errors: var(--rp-love); --icon-success: var(--rp-foam);
          --icon-warning: var(--rp-gold); --icon-information: var(--rp-pine);
          --icon-count-noti-enable-bg: var(--rp-love); --icon-count-noti-disable-bg: var(--rp-muted);
          --border: var(--rp-hl-med); --border-subtle: var(--rp-hl-low); --border-bold: var(--rp-hl-high);
          --border-disabled: var(--rp-hl-med); --border-focused: var(--rp-foam); --border-selected: var(--rp-pine);
          --border-errors: var(--rp-love); --border-success: var(--rp-foam); --border-warning: var(--rp-gold);
          --border-information: var(--rp-pine); --divider: var(--rp-hl-med); --divider-subtle: var(--rp-hl-low); --divider-bold: var(--rp-hl-high);
          --link: var(--rp-pine); --success: var(--rp-foam); --tab-txt: var(--rp-subtle); --tab-inactive: var(--rp-subtle); --tab-active: var(--rp-pine);
          --scrollbar: var(--rp-hl-high); --scrollbar-opacity: 0.55; --selection: var(--rp-selection); --selection-text: var(--rp-text);
          --blue-message: var(--rp-self-bubble); --blue-message-selected: var(--rp-self-selected);
          --blue-message-selected-border: var(--rp-self-bubble-border); --blue-message-border: var(--rp-self-bubble-border);
          --blue-message-action: var(--rp-self-selected); --blue-message-action-border: var(--rp-self-bubble-border);
          --blue-message-btn: var(--rp-overlay); --blue-message-btn-border: var(--rp-hl-med);
          --blue-quote: var(--rp-overlay); --blue-quote-selected: var(--rp-overlay); --blue-quote-border: var(--rp-self-bubble-border);
          --blue-quote-line: var(--rp-foam); --blue-link: var(--rp-pine); --blue-file-progress-track: var(--rp-overlay); --blue-message-shadow: transparent;
          --white-message: var(--rp-surface); --white-message-selected: var(--rp-hl-low); --white-message-selected-border: var(--rp-hl-med);
          --white-message-border: var(--rp-hl-med); --white-message-action: var(--rp-base); --white-message-action-border: var(--rp-hl-med);
          --white-message-btn: var(--rp-overlay); --white-message-btn-border: var(--rp-hl-med);
          --white-quote: var(--rp-hl-low); --white-quote-selected: var(--rp-hl-low); --white-quote-border: var(--rp-hl-med);
          --white-quote-line: var(--rp-iris); --white-link: var(--rp-pine); --white-file-progress-track: var(--rp-hl-med);
          --button-primary-normal: var(--rp-pine); --button-primary-hover: var(--rp-foam); --button-primary-pressed: var(--rp-pine);
          --button-primary-text: \(onColor); --button-secondary-normal: \(HexColor.rgba(cyan, 0.12));
          --button-secondary-hover: \(HexColor.rgba(cyan, 0.2)); --button-secondary-text: var(--rp-pine);
          --button-danger-normal: var(--rp-love); --button-danger-text: \(onColor);
          --input-field-bg-filled: var(--rp-overlay); --input-field-bg-filled-hover: var(--rp-hl-med);
          --field-bg-filled: var(--rp-overlay); --field-bg-filled-hover: var(--rp-hl-med);
          --field-bg-outline: var(--rp-surface); --field-bg-outline-hover: var(--rp-hl-low);
          --item-wa-hover: var(--rp-hl-low); --item-wa-select: var(--item-select); --brand-primary: var(--rp-pine);
        }

        html[data-zalo-theme="\(theme.id)"] body.zalo-theme {
          font-family: var(--zalo-ui-font) !important;
          font-weight: var(--zalo-ui-weight) !important;
          background-color: var(--rp-surface);
          color: var(--rp-text);
          -webkit-font-smoothing: antialiased;
        }

        html[data-zalo-theme="\(theme.id)"] body.zalo-theme .message-view,
        html[data-zalo-theme="\(theme.id)"] body.zalo-theme .card--text,
        html[data-zalo-theme="\(theme.id)"] body.zalo-theme .rich-input,
        html[data-zalo-theme="\(theme.id)"] body.zalo-theme .rich-text-input,
        html[data-zalo-theme="\(theme.id)"] body.zalo-theme .chat-box-input__content__input,
        html[data-zalo-theme="\(theme.id)"] body.zalo-theme .conv-message,
        html[data-zalo-theme="\(theme.id)"] body.zalo-theme .z-conv-message,
        html[data-zalo-theme="\(theme.id)"] body.zalo-theme .chat-info-general__item--title,
        html[data-zalo-theme="\(theme.id)"] body.zalo-theme .title-name {
          font-family: var(--zalo-ui-font) !important;
          font-weight: var(--zalo-ui-weight) !important;
        }

        html[data-zalo-theme="\(theme.id)"] body.zalo-theme b,
        html[data-zalo-theme="\(theme.id)"] body.zalo-theme strong,
        html[data-zalo-theme="\(theme.id)"] body.zalo-theme .font-semibold,
        html[data-zalo-theme="\(theme.id)"] body.zalo-theme [style*="font-weight: 500"],
        html[data-zalo-theme="\(theme.id)"] body.zalo-theme [style*="font-weight:500"] {
          font-weight: var(--zalo-ui-weight-strong) !important;
        }

        html[data-zalo-theme="\(theme.id)"] body.zalo-theme .message-view__blur__overlay,
        html[data-zalo-theme="\(theme.id)"] body.zalo-theme .message-view__blur__overlay_noavatar {
          background-image: var(--message-view-gradient) !important;
        }

        html[data-zalo-theme="\(theme.id)"] body.zalo-theme #main-tab { border-right: 1px solid var(--border); }
        html[data-zalo-theme="\(theme.id)"] body.zalo-theme.zalo-theme--darwin .nav__tabs__zalo {
          padding-top: 40px; padding-bottom: 16px; height: auto;
        }
        html[data-zalo-theme="\(theme.id)"] body.zalo-theme .leftbar-tab { color: var(--rp-subtle); }
        html[data-zalo-theme="\(theme.id)"] body.zalo-theme .leftbar-tab:hover,
        html[data-zalo-theme="\(theme.id)"] body.zalo-theme .leftbar-tab.selected { color: var(--rp-pine); }
        html[data-zalo-theme="\(theme.id)"] body.zalo-theme .card.me {
          background-color: var(--blue-message); border-color: var(--blue-message-border);
        }
        html[data-zalo-theme="\(theme.id)"] body.zalo-theme .card:not(.me) {
          background-color: var(--white-message); border-color: var(--white-message-border);
        }
        html[data-zalo-theme="\(theme.id)"] body.zalo-theme ::selection {
          background: var(--selection) !important; color: var(--selection-text) !important;
        }
        html[data-zalo-theme="\(theme.id)"] body.zalo-theme div::-webkit-scrollbar-thumb {
          background: var(--scrollbar) !important; opacity: var(--scrollbar-opacity) !important;
        }
        html[data-zalo-theme="\(theme.id)"] body.zalo-theme .setting-section:has(> .setting-section-content__theme) {
          display: none;
        }
        """
    }

    static func js(themeId: String) -> String {
        """
        /*
          Zalo Theme bootstrap — \(themeId)
        */
        (function () {
          const THEME = \(String(reflecting: themeId))
          const html = document.documentElement
          const body = document.body
          html.setAttribute('data-zalo-theme', THEME)
          body.classList.add('zalo-theme')
          body.classList.remove('zalo-maple-dawn', 'zalo-maple-dawn--darwin')
          if (html.getAttribute('data-zalo-os') === 'macOS') body.classList.add('zalo-theme--darwin')
          console.info('[zalo-theme]', THEME, 'active')
        })()
        """
    }

    static func patchIndexHTML(at appRoot: URL, themeId: String) throws {
        let indexURL = appRoot.appendingPathComponent("pc-dist/index.html")
        guard FileManager.default.fileExists(atPath: indexURL.path) else {
            throw InstallerError.failed("Missing \(indexURL.path)")
        }
        var html = try String(contentsOf: indexURL, encoding: .utf8)

        // Remove previous injections
        html = html.replacingOccurrences(
            of: #"<link[^>]*data-zalo-theme-tool="1"[^>]*>"#,
            with: "",
            options: .regularExpression
        )
        html = html.replacingOccurrences(
            of: #"<script[^>]*data-zalo-theme-tool="1"[^>]*></script>"#,
            with: "",
            options: .regularExpression
        )
        html = html.replacingOccurrences(
            of: #"<link[^>]*href="[^"]*zalo-theme/theme\.css"[^>]*>"#,
            with: "",
            options: .regularExpression
        )
        html = html.replacingOccurrences(
            of: #"<script[^>]*src="[^"]*zalo-theme/theme\.js"[^>]*></script>"#,
            with: "",
            options: .regularExpression
        )
        html = html.replacingOccurrences(
            of: #"<link[^>]*href="[^"]*zalo-maple-dawn/[^"]*"[^>]*>"#,
            with: "",
            options: .regularExpression
        )
        html = html.replacingOccurrences(
            of: #"<script[^>]*src="[^"]*zalo-maple-dawn/[^"]*"[^>]*></script>"#,
            with: "",
            options: .regularExpression
        )

        let link = "<link rel=\"stylesheet\" href=\"\(assetDirName)/theme.css\" \(marker)=\"1\">"
        let script = "<script src=\"\(assetDirName)/theme.js\" \(marker)=\"1\"></script>"

        if let range = html.range(of: "</head>", options: .caseInsensitive) {
            html.replaceSubrange(range, with: "\(link)\n</head>")
        } else {
            html += "\n\(link)\n"
        }
        if let range = html.range(of: "</body>", options: .caseInsensitive) {
            html.replaceSubrange(range, with: "\(script)\n</body>")
        } else {
            html += "\n\(script)\n"
        }

        // Attributes on <html>
        if html.range(of: #"data-zalo-os=""#, options: .regularExpression) != nil {
            html = html.replacingOccurrences(
                of: #"data-zalo-os="[^"]*""#,
                with: "data-zalo-os=\"macOS\"",
                options: .regularExpression
            )
        } else {
            html = html.replacingOccurrences(
                of: "<html",
                with: "<html data-zalo-os=\"macOS\"",
                options: [.caseInsensitive],
                range: html.range(of: "<html", options: .caseInsensitive)
            )
        }
        if html.range(of: #"data-zalo-theme=""#, options: .regularExpression) != nil {
            html = html.replacingOccurrences(
                of: #"data-zalo-theme="[^"]*""#,
                with: "data-zalo-theme=\"\(themeId)\"",
                options: .regularExpression
            )
        } else {
            html = html.replacingOccurrences(
                of: "<html",
                with: "<html data-zalo-theme=\"\(themeId)\"",
                options: [.caseInsensitive],
                range: html.range(of: "<html", options: .caseInsensitive)
            )
        }

        // Body classes
        if let bodyOpen = html.range(of: #"<body[^>]*>"#, options: [.regularExpression, .caseInsensitive]) {
            var tag = String(html[bodyOpen])
            tag = tag.replacingOccurrences(of: "zalo-maple-dawn--darwin", with: "")
            tag = tag.replacingOccurrences(of: "zalo-maple-dawn", with: "")
            if !tag.contains("zalo-theme--darwin") {
                if let classRange = tag.range(of: #"class="([^"]*)""#, options: .regularExpression) {
                    let full = String(tag[classRange])
                    let inner = full.dropFirst(7).dropLast()
                    let updated = "class=\"\(inner) zalo-theme zalo-theme--darwin\""
                    tag.replaceSubrange(classRange, with: updated)
                } else {
                    tag = tag.replacingOccurrences(of: "<body", with: "<body class=\"zalo-theme zalo-theme--darwin\"", options: .caseInsensitive)
                }
            } else if !tag.contains("zalo-theme") {
                tag = tag.replacingOccurrences(of: "zalo-theme--darwin", with: "zalo-theme zalo-theme--darwin")
            }
            html.replaceSubrange(bodyOpen, with: tag)
        }

        // CSP: allow unsafe-inline styles if style-src present
        if let cspRange = html.range(of: #"<meta[^>]*http-equiv="Content-Security-Policy"[^>]*>"#, options: [.regularExpression, .caseInsensitive]) {
            var meta = String(html[cspRange])
            if meta.contains("style-src"), !meta.contains("'unsafe-inline'") {
                meta = meta.replacingOccurrences(
                    of: #"style-src([^;"]*)"#,
                    with: "style-src$1 'unsafe-inline'",
                    options: .regularExpression
                )
                html.replaceSubrange(cspRange, with: meta)
            }
        }

        try html.write(to: indexURL, atomically: true, encoding: .utf8)
    }
}
